version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql_assistant_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sql_assistant_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@test-db:5432/sql_assistant_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=test-db
      - DB_PORT=5432
      - DB_NAME=sql_assistant_test
      - OPENAI_API_KEY=dummy_key_for_tests
      - JWT_PUBLIC_KEY=dummy_jwt_public_key_for_tests
      - TESTING=1
    volumes:
      - ./tests:/app/tests
      - ./sql_assistant:/app/sql_assistant
      - ./coverage.xml:/app/coverage.xml
    command: >
      bash -c "
        echo 'Setting up test database...' &&
        python tests/setup_test_db.py &&
        echo 'Running tests...' &&
        pytest tests/ --cov=sql_assistant --cov-report=xml --cov-report=term-missing -v
      "

volumes:
  test_postgres_data:
