name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sql_assistant_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov pytest-timeout ruff
        
    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/sql_assistant_test" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=dummy_key_for_tests" >> $GITHUB_ENV
        
    - name: Lint with ruff
      run: |
        ruff check sql_assistant tests
        
    - name: Run unit tests
      run: |
        PYTHONPATH=. pytest tests/unit/ --cov=sql_assistant --cov-report=xml
        
    - name: Setup database for integration tests
      run: |
        python db/import_data.py
        
    - name: Generate JWT Token
      run: |
        pwsh -Command "& { ./gen_jwt.ps1 -FleetId 1 | Out-File jwt_token.txt }"
        echo "JWT_TOKEN=$(cat jwt_token.txt)" >> $GITHUB_ENV

    - name: Run integration tests
      env:
        JWT_TOKEN: ${{ env.JWT_TOKEN }}
      run: |
        echo "Skipping integration tests temporarily"
        # pytest tests/integration/ --cov=sql_assistant --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
        
    - name: Lint frontend
      working-directory: ./frontend
      run: npm run lint
      
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Test frontend
      working-directory: ./frontend
      run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: yourusername/sql-assistant:latest
        cache-from: type=registry,ref=yourusername/sql-assistant:buildcache
        cache-to: type=registry,ref=yourusername/sql-assistant:buildcache,mode=max
